### ISSUE TITLE
Doesn't seem to work with spiderable

### ISSUE THREAD

**Issue by ivanbulanov** [lookback/meteor-seo#1]
The meta tags are there in the dynamic DOM but when I request the site to be rendered server-side by appending `?_escaped_fragment_=` to the URL, there are none. This kinda defies the purpose if Google bot cannot see the meta tags.

**Comment by johanbrook** [comment]
Hi @ivanbulanov. The tags seem to render in the DOM with Spiderable in the `test-app` directory. Can you provide a reproducable test case?

**Comment by johanbrook** [comment]
From my tests, this package is compatible with the latest Spiderable (2.0). I've updated the README to reflect that. Closing this for now.
