### ISSUE TITLE
How to add computed value to the meta object?

### ISSUE THREAD

**Issue by vfportero** [lookback/meteor-seo#17]
I'm triying to add the `geo.position` meta to a place on my seo configuration but i can't access to the data function on the meta object:

```js
seo: {
      title: function () {
        return this.data().Place.name
      },
      meta: {
        ICBM: 'latitude, longitude',
        geo: {
          position: `${this.data().Place.lat};${this.data().Place.lng}`,
        }
      }
    }
```

As object i can't access to the data() function to get the lat/lb and If I convert meta to a function is never called and the data is ignored.

How can set data variables to a custom meta property with meteor-seo?

Thanks

**Comment by johanbrook** [comment]
Yes, looks like functions aren't supported for that. Feel free to fix and file a PR if you want to – we (Lookback) aren't using this package internally anymore, so I'm limited in adding features.

**Comment by vfportero** [comment]
Done :)

Working on my meteor app right now.
