### ISSUE TITLE
Not sure how to apply to a route

### ISSUE THREAD

**Issue by Allerion** [lookback/meteor-seo#22]
Hi I'm a little confused how to apply this to a route. My method for creating routes is different to the documentation. I'm using the following:

    Router.route('/map/:_id/view', function () {

        if(Meteor.user()){
            this.layout('Internal');
        }else{
            this.layout('InternalIndex');
        }
        ....
    });

Tried using `this.seo({...})` but that didn't seem to work. Is there a way of doing it with routes declared in this fashion?

Many thanks

**Comment by johanbrook** [comment]
Hi!

The difference is that the format you're utilising is passing a function into the Iron Router framework and is calling functions on it, such as `this.layout, this.render`. The format in the documentation in this package is using an object structure where the plugin code can extract `seo` data from the object itself.

I haven't built the package around the function style format, and haven't looked into passing arbitrary `seo` data to a plugin in that format.

(I btw recommend switching to FlowRouter – Iron Router is kinda deprecated nowadays).

**Comment by Allerion** [comment]
Thanks for the feedback. Didn't realise Iron Router was deprecated.

**Comment by johanbrook** [comment]
No worries :)
