### ISSUE TITLE
spiderable required?

### ISSUE THREAD

**Issue by Pushplaybang** [lookback/meteor-seo#9]
It seems running this without spiderable (not that i'm there yet - still trying to get phantom into a docker container) is entirely pointless.  should spiderable not be a hard dependancy rather than a "compatibility note"?

**Comment by johanbrook** [comment]
@Pushplaybang Well, it's not "pointless" as the metadata still is inserted into the DOM. I agree on that Spiderable currently is the single existing solution for Meteor apps to have "pseudo server side rendering", but I'd hesitate to make Spiderable a hard dependency. Spiderable is a completely different feature, and out of scope of this package, imo.

**Comment by Pushplaybang** [comment]
fair enough, I've tried with about 4 flavours of spiderable so far - still with no real success.

I suppose my question is:  is there anything that actually will ever see the open graph stuff without having a solution like spiderable+phantom doing the pseudo SSR?

**Comment by johanbrook** [comment]
> I suppose my question is: is there anything that actually will ever see the open graph stuff without having a solution like spiderable+phantom doing the pseudo SSR?

No external crawler will, save for Google, which I think crawls JS generated content on the site. The "correct" way to do this is real server side rendering, but that won't land in Blaze for a while .. The option is to rewrite in React (landed in Meteor 1.2), but that won't make use of this package anyway :>

**Comment by Pushplaybang** [comment]
Totally get the react thing, and the 'correct way', and really like what you're doing with this, but its seems to be that however nicely it puts the meta in the head, without spiderable (at least until SSR lands in blaze) its  not tremendously useful.  Thus my original point.  Get it you're not keen to tie the two together, but you might want to be clearer in the ReadMe about that for other users.
